import pytest
from keygen_dictionary import DictionaryMaker


@pytest.fixture
def maker():
    return DictionaryMaker()


# ── _process_numbers ──────────────────────────────────────────────────────────

class TestProcessNumbers:
    def test_single_number_yields_prefixes_and_suffixes(self, maker):
        result = maker._process_numbers("1990")
        assert "1" in result
        assert "19" in result
        assert "199" in result
        assert "1990" in result
        assert "990" in result
        assert "90" in result

    def test_no_numbers_returns_empty(self, maker):
        assert maker._process_numbers("Main Street") == []

    def test_multiple_numbers_in_string(self, maker):
        result = maker._process_numbers("123 456")
        assert "12" in result
        assert "45" in result

    def test_single_digit_yields_only_itself(self, maker):
        result = maker._process_numbers("5")
        assert result == ["5"]

    def test_no_noise_repetitions(self, maker):
        result = maker._process_numbers("111")
        # should not contain repeated digit combos like "111" generated by product
        assert all(len(set(r)) > 0 for r in result)


# ── _process_name ─────────────────────────────────────────────────────────────

class TestProcessName:
    def test_full_name_contains_parts(self, maker):
        result = maker._process_name("John Doe")
        assert "John" in result
        assert "Doe" in result

    def test_full_name_contains_initials(self, maker):
        result = maker._process_name("John Doe")
        assert "J" in result
        assert "D" in result

    def test_full_name_contains_joined(self, maker):
        result = maker._process_name("John Doe")
        assert "JohnDoe" in result

    def test_single_word(self, maker):
        result = maker._process_name("Alice")
        assert "Alice" in result
        assert "A" in result

    def test_returns_deduped_list(self, maker):
        result = maker._process_name("John Doe")
        assert len(result) == len(set(result))


# ── _process_date ─────────────────────────────────────────────────────────────

class TestProcessDate:
    def test_dash_format_splits_parts(self, maker):
        result = maker._process_date("01-01-1990")
        assert "01" in result
        assert "1990" in result

    def test_slash_format_splits_parts(self, maker):
        result = maker._process_date("01/01/1990")
        assert "01" in result
        assert "1990" in result

    def test_four_digit_year_yields_century_and_decade(self, maker):
        result = maker._process_date("01-01-1990")
        assert "19" in result
        assert "90" in result

    def test_no_separator_returns_empty(self, maker):
        result = maker._process_date("01011990")
        assert result == []

    def test_returns_deduped_list(self, maker):
        result = maker._process_date("01-01-1990")
        assert len(result) == len(set(result))


# ── _process_identification ───────────────────────────────────────────────────

class TestProcessIdentification:
    def test_multi_digit_yields_prefixes(self, maker):
        result = maker._process_identification("12345")
        assert "1" in result
        assert "12" in result
        assert "123" in result
        assert "1234" in result

    def test_full_number_not_in_result(self, maker):
        # range stops before len(number), so full string excluded
        result = maker._process_identification("12345")
        assert "12345" not in result

    def test_single_char_returns_itself(self, maker):
        result = maker._process_identification("5")
        assert "5" in result

    def test_returns_deduped_list(self, maker):
        result = maker._process_identification("11223")
        assert len(result) == len(set(result))


# ── _process_domain ───────────────────────────────────────────────────────────

class TestProcessDomain:
    def test_splits_on_dot(self, maker):
        result = maker._process_domain("example.com")
        assert "example" in result
        assert "com" in result
        assert "example.com" in result

    def test_subdomain(self, maker):
        result = maker._process_domain("mail.example.com")
        assert "mail" in result
        assert "example" in result
        assert "com" in result


# ── _shannon_entropy ──────────────────────────────────────────────────────────

class TestShannonEntropy:
    def test_empty_string_is_zero(self):
        assert DictionaryMaker._shannon_entropy("") == 0.0

    def test_uniform_string_is_zero(self):
        assert DictionaryMaker._shannon_entropy("aaaa") == 0.0

    def test_entropy_increases_with_variety(self):
        low  = DictionaryMaker._shannon_entropy("aaaa")
        mid  = DictionaryMaker._shannon_entropy("aabb")
        high = DictionaryMaker._shannon_entropy("abcd")
        assert low < mid < high

    def test_predictable_less_than_random(self):
        # "password" has repeated chars → lower entropy than all-unique
        assert DictionaryMaker._shannon_entropy("password") < \
               DictionaryMaker._shannon_entropy("xK9@mN2q")


# ── _passes_length_filter ─────────────────────────────────────────────────────

class TestLengthFilter:
    def test_no_limits_always_passes(self, maker):
        assert maker._passes_length_filter("hi")
        assert maker._passes_length_filter("averylongpassword123")

    def test_min_length_excludes_short(self, maker):
        maker.min_length = 8
        assert not maker._passes_length_filter("short")
        assert maker._passes_length_filter("longenough")

    def test_max_length_excludes_long(self, maker):
        maker.max_length = 8
        assert not maker._passes_length_filter("toolongpassword")
        assert maker._passes_length_filter("short")

    def test_exact_min_passes(self, maker):
        maker.min_length = 5
        assert maker._passes_length_filter("hello")

    def test_exact_max_passes(self, maker):
        maker.max_length = 5
        assert maker._passes_length_filter("hello")

    def test_both_limits(self, maker):
        maker.min_length = 4
        maker.max_length = 8
        assert not maker._passes_length_filter("abc")
        assert maker._passes_length_filter("abcd")
        assert maker._passes_length_filter("abcdefgh")
        assert not maker._passes_length_filter("abcdefghi")


# ── _apply_leet ───────────────────────────────────────────────────────────────

class TestApplyLeet:
    def test_admin_gets_leet_variant(self, maker):
        maker.tokens = ["admin"]
        maker._apply_leet()
        assert "4dm1n" in maker.tokens

    def test_no_duplicates_added(self, maker):
        maker.tokens = ["admin"]
        maker._apply_leet()
        assert maker.tokens.count("4dm1n") == 1

    def test_no_leet_when_no_substitutable_chars(self, maker):
        before = set(maker.tokens)
        maker.tokens = ["xyz"]
        maker._apply_leet()
        # "xyz" has no a/e/i/o/s — no variant should be added
        added = set(maker.tokens) - {"xyz"}
        assert "xyz" not in added

    def test_all_substitutions(self, maker):
        maker.tokens = ["aeiOS"]
        maker._apply_leet()
        assert "43105" in maker.tokens
